# Workflow to publish Godot HTML5 games to GitHub Pages
#
# Make sure your project is configured for Web export
# to the path `build/web`.

name: 'Publish to GitHub Pages'

env:
  GODOT_VERSION: 4.5.1 # Remember to manually set image to this version below.

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      image: barichello/godot-ci:4.5.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Move HTML5 templates into position
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Create staging directory
        run: mkdir -v -p build/web

      - name: Build
        run: godot -v --export-release --headless "Web" web/index.html project.godot

      - name: Compress project
        run: |
          cd web
          wget https://raw.githubusercontent.com/nodeca/pako/master/dist/pako_inflate.min.js
          gzip -f index.wasm
          gzip -f index.pck
          FIND="<script type='text/javascript' src='index.js'></script>"
          REPLACE="<script type=\"text/javascript\" src=\"pako_inflate.min.js\"></script>$FIND"
          sed -i -e "s@$FIND@$REPLACE@" index.html
          FIND="function loadFetch(file, tracker, fileSize, raw) {"
          REPLACE=$FIND" var p_file=file if(file.endsWith(".wasm")||file.endsWith(".pck")){file+=".gz"}tracker[file]={total:fileSize||0,loaded:0,done:false,};return fetch(file).then(function(response){if(!response.ok){return Promise.reject(new Error(`Failed loading file'${file}'`))}const tr=getTrackedResponse(response,tracker[p_file]);return Promise.resolve(tr.arrayBuffer().then(buffer=>{return new Response(pako.inflate(buffer),{headers:tr.headers})}))})}
          sed -i -e "s@$FIND@$REPLACE@" index.js
          FIND="this.preload=function(pathOrBuffer,destPath,fileSize){let buffer=null;if(typeof pathOrBuffer==='string'){const me=this;return this.loadPromise(pathOrBuffer,fileSize).then(function(buf){me.preloadedFiles.push({path:destPath||pathOrBuffer,buffer:buf,});return Promise.resolve()})}else if(pathOrBuffer instanceof ArrayBuffer){buffer=new Uint8Array(pathOrBuffer)}else if(ArrayBuffer.isView(pathOrBuffer)){buffer=new Uint8Array(pathOrBuffer.buffer)}if(buffer){this.preloadedFiles.push({path:destPath,buffer:pathOrBuffer,});return Promise.resolve()}return Promise.reject(new Error('Invalid object for preloading'))};"
          REPLACE="this.preload=function(pathOrBuffer,destPath,fileSize){let buffer=null;if(typeof pathOrBuffer==='string'){const me=this;return this.loadPromise(pathOrBuffer,fileSize).then(function(buf){buf.arrayBuffer().then(data=>{me.preloadedFiles.push({path:destPath||pathOrBuffer,buffer:data,})})return Promise.resolve()})}else if(pathOrBuffer instanceof ArrayBuffer){buffer=new Uint8Array(pathOrBuffer)}else if(ArrayBuffer.isView(pathOrBuffer)){buffer=new Uint8Array(pathOrBuffer.buffer)}if(buffer){this.preloadedFiles.push({path:destPath,buffer:pathOrBuffer,});return Promise.resolve()}return Promise.reject(new Error('Invalid object for preloading'))};"
          sed -i -e "s@$FIND@$REPLACE@" index.js

      - name: Add coi-service-worker
        run: |
          git clone https://github.com/gzuidhof/coi-serviceworker.git
          mv coi-serviceworker/coi-serviceworker.js web/coi-serviceworker.js
          sed -i '3 i <script src="coi-serviceworker.js"></script>' web/index.html
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web
          force_orphan: true
          user_name: 'github-ci[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Publish to gh-pages'

